# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_USER

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                login_path: /login
                check_path: /login_check
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                login_path: /login
                failure_path: /login

                oauth_user_provider:
                    service: my_user_provider
            logout: true
            anonymous: true

        login:
            pattern: ^/login$
            security: false

            remember_me:
                key: "%secret%"
                lifetime: 31536000
                path: /
                domain: ~

    access_control:
        - {path: ^/[a-z][a-z]/home/messages, roles: ROLE_USER}
        - {path: ^/, roles: IS_AUTHENTICATED_ANONYMOUSLY}