# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    my_user_provider:
        class: AppBundle\Security\FOSUBUserProvider
        arguments: [@fos_user.user_manager.default, {facebook: facebook_id, google: google_id}]

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: [@router, %app_locales%, %locale%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ["@translator.default", "@twig"]
        tags:
            - { name: kernel.event_subscriber }
    app.ajax_listener:
        class: AppBundle\EventListener\AjaxListener
        arguments: ["%ajax_configuration%", "@app.courses.ajax.service", "@app.home.messages.ajax.service", "@app.page.controls.ajax.service", "@app.create.course.ajax.service"]
        tags:
            - { name: kernel.event_subscriber }
    app.entity.life.cycle.listener:
        class: AppBundle\EventListener\EntityLifeCycleListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.courses.ajax.service:
        class: AppBundle\Service\Ajax\Teach\CoursesAjaxService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@twig", "%standard_query_limit%", "%standard_pagination_max%"]
    app.home.messages.ajax.service:
        class: AppBundle\Service\Ajax\Home\MessagesAjaxService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@twig"]
    app.page.controls.ajax.service:
        class: AppBundle\Service\Ajax\PageControlsAjaxService
        arguments: ["@fos_user.entity_manager", "@security.token_storage", "@app.transform.manager", "@twig", "%standard_query_limit%", "%standard_pagination_max%"]
    app.create.course.ajax.service:
        class: AppBundle\Service\Ajax\Teach\CreateCourseAjaxService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@app.validator.validator"]

    app.transformer.messages:
        class: AppBundle\Transformer\MessagesTransformer
        arguments: ["@twig"]
    app.transformer.course.reviews:
        class: AppBundle\Transformer\CourseReviewsTransformer
        arguments: ["@twig"]
    app.transformer.courses:
        class: AppBundle\Transformer\CoursesTransformer
        arguments: ["@twig", "%standard_query_limit%", "%standard_pagination_max%"]
    app.transform.manager:
        class: AppBundle\Transformer\TransformManager
        arguments: ["@app.transformer.messages", "@app.transformer.course.reviews", "@app.transformer.courses"]

    app.validator.validator:
        class: AppBundle\Validator\Validator
        arguments: ["@doctrine.orm.entity_manager", "%kernel.root_dir%"]

    app.twig.date.extension:
        class: Twig_Extensions_Extension_Date
        arguments: ["@translator.default"]
        tags:
            - {name: "twig.extension"}