# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    my_user_provider:
        class: AppBundle\Security\FOSUBUserProvider
        arguments: [@fos_user.user_manager.default, {facebook: facebook_id, google: google_id}]

    app.locale_listener:
        class: AppBundle\EventListener\LocaleListener
        arguments: [@router, @session, %app_locales%, %locale%]
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
    app.exception_listener:
        class: AppBundle\EventListener\ExceptionListener
        arguments: ["@translator.default", "@twig"]
        tags:
            - { name: kernel.event_subscriber }
    app.ajax_listener:
        class: AppBundle\EventListener\AjaxListener
        arguments: ["%ajax_configuration%", "@app.courses.ajax.service", "@app.home.messages.ajax.service", "@app.page.controls.ajax.service", "@app.create.course.ajax.service", "@app.profile.ajax.service", "@app.course.collection.ajax.service", "@app.learn.study.ajax.service"]
        tags:
            - { name: kernel.event_subscriber }
    app.entity.life.cycle.listener:
        class: AppBundle\EventListener\EntityLifeCycleListener
        arguments: ["@security.token_storage"]
        tags:
            - { name: doctrine.event_subscriber, connection: default }

    app.courses.ajax.service:
        class: AppBundle\Service\Ajax\Teach\CoursesAjaxService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@twig", "%standard_query_limit%", "%standard_pagination_max%"]
    app.home.messages.ajax.service:
        class: AppBundle\Service\Ajax\Home\MessagesAjaxService
        arguments: ["@doctrine.orm.entity_manager", "@twig", "@app.authorization.service"]
    app.page.controls.ajax.service:
        class: AppBundle\Service\Ajax\PageControlsAjaxService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@app.transform.manager", "@twig", "@session", "%standard_query_limit%", "%standard_pagination_max%"]
    app.create.course.ajax.service:
        class: AppBundle\Service\Ajax\Teach\CreateCourseAjaxService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@app.validator.validator", "@app.transform.manager", "@router", "@twig"]
    app.profile.ajax.service:
        class: AppBundle\Service\Ajax\Home\ProfileAjaxService
        arguments: ["@doctrine.orm.entity_manager", "@security.token_storage", "@app.validator.validator", "@app.transform.manager"]
    app.course.collection.ajax.service:
        class: AppBundle\Service\Ajax\Learn\CourseCollectionAjaxService
        arguments: ["@doctrine.orm.entity_manager", "@app.authorization.service"]
    app.learn.study.ajax.service:
        class: AppBundle\Service\Ajax\Learn\StudyAjaxService
        arguments: ["@app.authorization.service", "@doctrine.orm.entity_manager", "@session", "@twig"]

    app.transformer.messages:
        class: AppBundle\Transformer\MessagesTransformer
        arguments: ["@twig"]
    app.transformer.course.reviews:
        class: AppBundle\Transformer\CourseReviewsTransformer
        arguments: ["@twig"]
    app.transformer.courses:
        class: AppBundle\Transformer\CoursesTransformer
        arguments: ["@twig", "%standard_query_limit%", "%standard_pagination_max%", "@app.authorization.service", "@doctrine.orm.entity_manager"]
    app.transformer.course.teachers:
        class: AppBundle\Transformer\CourseTeachersTransformer
        arguments: ["@twig"]
    app.transformer.course.announcements:
        class: AppBundle\Transformer\CourseAnnouncementsTransformer
        arguments: ["@twig"]
    app.transformer.course.provider:
        class: AppBundle\Transformer\CourseProvidersTransformer
        arguments: ["@twig"]
    app.transformer.course.questions:
        class: AppBundle\Transformer\CourseQuestionsTransformer
        arguments: ["@twig"]
    app.transformer.profile:
        class: AppBundle\Transformer\ProfileTransformer
        arguments: ["@twig"]
    app.transformer.profile.education:
        class: AppBundle\Transformer\ProfileEducationTransformer
        arguments: ["@twig"]
    app.transformer.course.collection.items:
        class: AppBundle\Transformer\CourseCollectionItemsTransformer
        arguments: ["@twig"]
    app.transformer.reports:
        class: AppBundle\Transformer\ReportsTransformer
        arguments: ["@twig"]
    app.transform.manager:
        class: AppBundle\Transformer\TransformManager
        arguments: ["@app.transformer.messages", "@app.transformer.course.reviews", "@app.transformer.courses", "@app.transformer.course.teachers", "@app.transformer.course.announcements", "@app.transformer.course.provider", "@app.transformer.course.questions", "@app.transformer.profile", "@app.transformer.profile.education", "@app.transformer.course.collection.items", "@app.transformer.reports"]

    app.validator.validator:
        class: AppBundle\Validator\Validator
        arguments: ["@doctrine.orm.entity_manager", "%kernel.root_dir%"]

    app.twig.date.extension:
        class: Twig_Extensions_Extension_Date
        arguments: ["@translator.default"]
        tags:
            - {name: "twig.extension"}

    app.twig.order.extension:
        class: AppBundle\Twig\OrderExtension
        public: false
        tags:
            - {name: "twig.extension"}

    app.authorization.service:
        class: AppBundle\Authorization\AuthorizationService
        arguments: ["@security.token_storage", "@security.authorization_checker"]